version: '2'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - api
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'